#Core
application-version: @project.version@
application-description: @project.description@

#Open Api
springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:pricedb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect